### ISSUE TITLE
Not work if the C++ version is set to -std 11xx

### ISSUE THREAD

**Issue by Malkitti** [neubig/pgibbs#1]

**Comment by Malkitti** [comment]
As it uses AUTOCONF, We need to set  C++  version manually.

**Comment by neubig** [comment]
Thanks for pointing this out. This doesn't break in my environment so I'm not sure how to fix it, but if you create a fix and send a pull request I'll incorporate it.

**Comment by Malkitti** [comment]
It need to be compiled in following way.
automake
libtoolize
aclocal
autoconf
In the configure.am we need to add  AX_CHECK_COMPILE_FLAG([-std=c++0x], [
                        CXXFLAGS="$CXXFLAGS -std=c++0x"])

or 
ax_cxx_compile_stdcxx_11

**Comment by neubig** [comment]
OK, I think this has been fixed in the most recent version by adding a line to configure.ac, try it out and see if it works for you.
